name: CI Jifa

#inicializador
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

#tarefas para executar antes do build
jobs:
  lint:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar ESLint globalmente
        run: |
          npm install -g eslint
          eslint assets/js --ext .js



  cypress:

#build do projeto
build:

